<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Trevvos.Worker-b84378ba-92e3-4757-ba74-92220d421b89</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trevvos.Application\Trevvos.Application.csproj" />
    <ProjectReference Include="..\Trevvos.Infrastructure\Trevvos.Infrastructure.csproj" />
  </ItemGroup>
</Project>
